// <auto-generated />
namespace Traveler.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Travel_Updated_User_Ref : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Travel_Updated_User_Ref));
        
        string IMigrationMetadata.Id
        {
            get { return "201611101029586_Travel_Updated_User_Ref"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
