// <auto-generated />
namespace Traveler.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class city_in_travel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(city_in_travel));
        
        string IMigrationMetadata.Id
        {
            get { return "201611101636121_city_in_travel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
