// <auto-generated />
namespace Traveler.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class city_in_travel1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(city_in_travel1));
        
        string IMigrationMetadata.Id
        {
            get { return "201611101717002_city_in_travel1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
